---

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - /etc/docker/

- name: Create docker config file
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker.daemon.config | to_nice_json }}"
  notify: restart_docker