---

- name: Install required packages
  yum:
    name:
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm
    state: latest

- name: Add repositories
  template:
    src: kubernetes.repo.tmpl
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
    update_cache: yes
